### ISSUE TITLE
Не удаляются .old ядра, установленные по make install

### ISSUE THREAD

**Issue by trupanka** [megabaks/kernel-cleaner#1]
kernel-cleaner удаляет только System.map._.old, оставляя config._.old и vmlinuz.*.old в /boot

**Comment by megabaks** [comment]
и не должен удалять - имя файла ничего не значит, если ядро корректно.
и таки нужен выхлоп
kernel-cleaner -l
и список того, что должно быть по-твоему удалено

**Comment by trupanka** [comment]
Странные у тебя представления о корректности. Я сам выбираю ядро. Выхлоп давал на ЛОР-е. Если ты просишь потестить, а потом включаешь игнор, то сам и пользуйся своей поделкой. Из 4 запусков ни разу корректно не сработала и ни разу не выполнила свое предназначение - удалять трэш.

**Comment by megabaks** [comment]
не странные - имя файла ничего не значит.
в чём проблема здесь запостить выхлоп?
и какие претензии ко мне, если у тебя флешка полурабочая?
